# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
markdown: kramdown

# Setup
title:               ssexess
tagline:             'Palindromische Universalitäten'
description:         'Im Rausch der Sinne'
url:                 http://ssexess.de

baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Rachel Bühlmann
  url:               https://ssexess.de
  email:             rachelbuehlmann@gmail.com

sass:
  style: :compressed

# Custom vars
version:             0.1.2
